"""
daily_digest.py -- the "do it for me every day" piece.

Reads the filters you saved in the web UI (saved_search.json), runs the search,
and writes an HTML digest of the best deals to `digest.html`. If SMTP env vars
are set, it also emails the digest to you.

Schedule it to run once a day:

  macOS / Linux (crontab -e):
    0 8 * * *  cd /path/to/redfin-deal-finder && /path/to/python daily_digest.py

  Windows (Task Scheduler):
    Program:   python
    Arguments: daily_digest.py
    Start in:  C:\\path\\to\\redfin-deal-finder

Optional email (set these as environment variables before running):
    SMTP_HOST, SMTP_PORT (default 587), SMTP_USER, SMTP_PASS, DIGEST_TO
"""

from __future__ import annotations

import json
import os
import smtplib
import ssl
from email.mime.text import MIMEText

import redfin_client

HERE = os.path.dirname(__file__)
SAVED = os.path.join(HERE, "saved_search.json")
OUT = os.path.join(HERE, "digest.html")
TOP_N = 25


def build_html(result: dict) -> str:
    rows = []
    for h in result["listings"][:TOP_N]:
        reasons = " · ".join(h.get("deal_reasons", [])) or "—"
        price = f"${int(h['price']):,}" if h.get("price") else "—"
        ppsf = f"${int(h['ppsf'])}/sqft" if h.get("ppsf") else "—"
        rows.append(f"""
          <tr>
            <td style="font-weight:800;color:#c01f2f;font-size:18px">{h['deal_score']}</td>
            <td><b>{price}</b><br><span style="color:#697086;font-size:12px">{ppsf}
                · {int(h['dom']) if h.get('dom') is not None else '—'} days</span></td>
            <td>{h['address']}<br><span style="color:#697086;font-size:12px">
                {', '.join(filter(None,[h.get('city'),h.get('state'),h.get('zip')]))}</span></td>
            <td style="font-size:12px;color:#3a4153">{reasons}</td>
            <td><a href="{h.get('url','')}">View ↗</a></td>
          </tr>""")
    banner = (
        f'<p style="color:#8a6a16;background:#fff7e6;padding:10px;border-radius:8px">'
        f'⚠️ {result["message"]}</p>' if result["source"] == "demo" else ""
    )
    return f"""<!doctype html><html><body style="font-family:system-ui,Arial;max-width:820px;margin:auto">
      <h2>🏠 Your Redfin deals — top {min(TOP_N, result['count'])} of {result['count']}</h2>
      {banner}
      <table cellpadding="9" style="border-collapse:collapse;width:100%">
        <tr style="text-align:left;border-bottom:2px solid #eee">
          <th>Score</th><th>Price</th><th>Address</th><th>Why it's a deal</th><th></th></tr>
        {''.join(rows)}
      </table>
      <p style="color:#9aa1b2;font-size:12px">Generated by Redfin Deal Finder.
         Deal score is a heuristic from $/sqft vs. the area median, days on market, and relative price.</p>
    </body></html>"""


def maybe_email(html: str, count: int) -> None:
    host = os.environ.get("SMTP_HOST")
    to = os.environ.get("DIGEST_TO")
    if not (host and to):
        print("  (email skipped — set SMTP_HOST and DIGEST_TO to enable)")
        return
    msg = MIMEText(html, "html")
    msg["Subject"] = f"🏠 {count} Redfin deals for you today"
    msg["From"] = os.environ.get("SMTP_USER", to)
    msg["To"] = to
    with smtplib.SMTP(host, int(os.environ.get("SMTP_PORT", "587"))) as server:
        server.starttls(context=ssl.create_default_context())
        if os.environ.get("SMTP_USER"):
            server.login(os.environ["SMTP_USER"], os.environ["SMTP_PASS"])
        server.send_message(msg)
    print(f"  emailed digest to {to}")


def main() -> None:
    if not os.path.exists(SAVED):
        raise SystemExit(
            "No saved_search.json found. Open the web UI (python app.py), set your "
            "filters, and click 'Save ⭐' first."
        )
    with open(SAVED, encoding="utf-8") as fh:
        filters = json.load(fh)

    result = redfin_client.search(filters, allow_live=True)
    html = build_html(result)
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(html)
    print(f"  wrote {OUT} ({result['count']} matches, source={result['source']})")
    maybe_email(html, result["count"])


if __name__ == "__main__":
    main()
